services:
  web:
    build: .
    image: findsmart-web:latest
    container_name: findsmart-app
    ports:
      - "3000:8000" # Mapea el puerto 3000 para que NPM lo vea
    env_file:
      - .env  # <--- ESTO ES VITAL
    environment:
      # Sobrescribimos REDIS_HOST para que apunte al contenedor de Redis en la red interna de Docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: findsmart-redis
    ports:
      - "6379:6379" # Opcional: expone redis al host si lo necesitas para debug externo
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
