version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      # Imagen estable con Node 22 para evitar errores de crypto
      - image: cimg/node:22.13.1
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm ci
      - run:
          name: "Build Project"
          command: npm run build # React Router v7
      - persist_to_workspace:
          root: ~/project
          paths:
            - build # Carpeta generada por React Router v7

  deploy:
    docker:
      - image: cimg/base:2023.09
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - "SHA256:zZGf4Xb/l6SnQ8l8RlgiXg9TjZDYAAHpi8GvkZN+3zA" # Tu huella digital
      - run:
          name: "Add VPS to known_hosts"
          command: ssh-keyscan $IP >> ~/.ssh/known_hosts
      - run:
          name: "Deploy using rsync"
          # Sincronizamos la carpeta 'build' directamente a la ruta del VPS
          command: rsync -avz --delete ~/project/build/ $USER@$IP:/var/www/website-findSmart/build/
      - run:
          name: "Restart Service"
          # Reiniciamos el servicio usando PM2 con el usuario circleci
          command: ssh $USER@$IP 'source ~/.bashrc && pm2 restart findSmart-web'

workflows:
  test-build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master # Ajustado a tu rama master
