version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm ci
      - run:
          name: "Build Project"
          command: npm run build

      # Guardamos la carpeta 'dist' (que es la que genera Vite)
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

  deploy:
    docker:
      - image: cimg/base:2023.09
    steps:
      - attach_workspace:
          at: ~/project

      - add_ssh_keys:
          fingerprints:
            - "SHA256:zZGf4Xb/l6SnQ8l8RlgiXg9TjZDYAAHpi8GvkZN+3zA"

      - run:
          name: "Add VPS to known_hosts"
          command: ssh-keyscan $IP >> ~/.ssh/known_hosts

      # Copiamos la carpeta dist/ al servidor (¡ya sin la ruta web!)
      - run:
          name: "Deploy using rsync"
          command: rsync -avz --delete ~/project/dist/ $USER@$IP:/var/www/website-findSmart/dist/

      - run:
          name: "Restart Service"
          command: ssh $USER@$IP 'source ~/.bashrc && pm2 restart findSmart-web'

workflows:
  test-build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
